server:
  port: 80

spring:
  application:
    name: cloud-order-openfeign-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
# feign client timeout default 1000ms
ribbon:
  # config read timeout 5000ms, 讀取資料
  ReadTimeout: 5000
  # config connect timeout 5000ms, 建立連線
  ConnectTimeout: 5000