server:
  port: 3344

spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:smoming/springcloud-config.git
          uri: https://github.com/smoming/springcloud-config.git
          search-paths: #搜尋目標
            - springcloud-config
      # 讀取分支 default read master
      #label: master

eureka:
  instance:
    instance-id: config3344
    #顯示 IP info
    prefer-ip-address: true
    #發送給 eureka server 通訊告知服務情況, default: 30s
    #lease-renewal-interval-in-seconds: 1
    #發送給 eureka server 最後一次通訊告知服務情況, default: 90s
    #lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #單機
      #defaultZone: http://localhost:7001/eureka/
      #叢集
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/