server:
  port: 8401

spring:
  application:
    name: cloud-nacos-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719  

# sentinel nacos 配置to database
#      datasource:
#        ds1: 
#          nacos:
#            server-addr: localhost:8848 
#            data-id: ${spring.application.name}
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*' 