server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #叢集指向其他eureka server
      defaultZone: http://eureka7001.com:7001/eureka/
      #非叢集指向自己eureka server
      #defaultZone: http://eureka7001.com:7001/eureka/
#  server:
#    #關閉自我保護機制, default: true
#    enable-self-preservation: false
#    #調整偵測服務健康度區間, default: 90000ms
#    eviction-interval-timer-in-ms: 2000