server:
  port: 83

spring:
  application:
    name: cloud-nacos-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 

service-url:
  nacos-user-service: http://cloud-nacos-payment-service

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*' 