server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh1
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    instance-id: gateway9527
    #顯示 IP info
    prefer-ip-address: true
    #發送給 eureka server 通訊告知服務情況, default: 30s
    #lease-renewal-interval-in-seconds: 1
    #發送給 eureka server 最後一次通訊告知服務情況, default: 90s
    #lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #單機
      #defaultZone: http://localhost:7001/eureka/
      #叢集
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/